### ISSUE TITLE
How to update existing object?

### ISSUE THREAD

**Issue by gashcrumb** [redhat-ipaas/ipaas-rest#199]
Currently the UI tries to do a PUT but that fails at the OPTIONS request (snipped out all the javascript gobbledegook for ya):

```
OPTIONS https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/api/v1/integrations/3 403 (Forbidden)

save-or-add-step:1 XMLHttpRequest cannot load https://ipaas-staging.b6ff.rh-idev.openshiftapps.com/api/v1/integrations/3. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. The response had HTTP status code 403.
```

The response back from this OPTIONS request doesn't have any CORS headers, but we're sending:

```
Access-Control-Request-Headers:authorization,content-type
Access-Control-Request-Method:PUT
```

We should be using a PUT to update, right?

**Comment by KurtStam** [comment]
Yeah PUT should work. Looks like CORS is not configured to handle localhost? "Origin 'http://localhost:4200' is therefore not allowed access."

**Comment by chirino** [comment]
hum..

**Comment by chirino** [comment]
@gashcrumb I think #199 should fix it, but I noticed that saving an integration does post with lots of query params

<img width="1242" alt="red_hat_ipaas" src="https://cloud.githubusercontent.com/assets/103255/24058863/0fc210c0-0b23-11e7-8abd-0838e399fe69.png">

**Comment by gashcrumb** [comment]
Yeah, I've a commit locally that might fix that post call, haven't been
able to test it though, thanks for the fix!

**Comment by gashcrumb** [comment]
Pushed my changes but still getting a 403, am assuming probably staging hasn't picked this up yet.
